public enum StackableType
{
    None = 0,
    Money = 1,
    Shawarma = 2,
    ShawarmaClassic = 3,
    ShawarmaKorean = 4,
    ShawarmaSpicy = 5,
    ShawarmaPork = 6,
    ShawarmaCheese = 7,
    ShawarmaVillage = 8,
    ShawarmaBeef = 9,
    ShawarmaSea = 10,
    ShawarmaBigLunch = 11,
    ShawarmaStrange = 12,
    ShawarmaVegetarian = 13,
    ShawarmaMeat = 14,
    ShawarmaMorning = 15,
    ShawarmaPorkPlus = 16,
}
